### ISSUE TITLE
Cannot run with the OTBR container from official image

### ISSUE THREAD

**Issue by nduongn** [kyberpunk/openthread#26]
Hi, The instruction in readme.md file to install border router with MQTT-SN gateway using openthread/otbr with --ncp-path flag but the official OTBR change to use --radio-url flag. Can you update the tutorial to use with the correct OTBR commit/docker image that can run the MQTT-SN client examples?
1. Git commit id: 72497df
2. IEEE 802.15.4 hardware platform: Raspberry Pi 3B, KW41Z

Thanks.

**Comment by kyberpunk** [comment]
Hello. Yes, I will merge latest openthread upstream and update examples. Thank you.

**Comment by kyberpunk** [comment]
@andynnd I've merged latest changes and fixed guide to follow RCP design. It should now work with latest official docker image. Sorry for the delay.

However mqtt capabilities are not needed on border router (RCP/NCP) side. So if it changes again you can build RCP from official sources and use this project just on client devices, it should be more or less compatible.
